name = "SIIP-Package"
uuid = "bed98974-b02a-5e2f-9ee0-a103f5c450dd"
authors = ["YOUR_NAME"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
DocStringExtensions = "~0.8, ~0.9"
julia = "^1.6"
