abstract type AbstractTechnologyFormulation end

abstract type InvestmentTechnologyFormulation <: AbstractTechnologyFormulation end
abstract type TechnologyOperationsFormulation <: AbstractTechnologyFormulation end
abstract type TechnologyFeasibilityFormulation <: AbstractTechnologyFormulation end
